apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notary
  annotations:
    fluxcd.io/automated: "false"
  namespace: supplychain-ns
spec:
  releaseName: notary
  interval: 1m
  chart:
    spec:
      chart: platforms/r3-corda/charts/notary
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
  values:
    nodeName: notary
    replicas: 1
    metadata:
      namespace: supplychain-ns
    image:
      containerName: ghcr.io/hyperledger/bevel-corda:4.7-linuxkit
      initContainerName: ghcr.io/hyperledger/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: doorman.corda.5gzorro.smartcommunitylab.it
      networkmapCertAlias: networkmap.corda.5gzorro.smartcommunitylab.it
    nodeConf:
      p2p:
        url: notary.supplychain-ns
        port: 10002
      ambassadorAddress: notary.corda.5gzorro.smartcommunitylab.it:15010
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Notary,OU=Notary,L=London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
            
      notary:
        validating: True
        serviceLegalName: O=Notary Service,OU=Notary,L=London,C=GB
       
      detectPublicIp: false
      database:
        exportHibernateJMXStatistics: false
      dbUrl: notarydb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://notarydb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: https://networkmap.corda.5gzorro.smartcommunitylab.it
      doormanURL: https://doorman.corda.5gzorro.smartcommunitylab.it
      compatibilityZoneURL:
      jarVersion: 4.7
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: notaryoperations
          permissions: [ALL]

    cordapps:
      getcordapps: true
      jars:
        - url: https://maven.pkg.github.com/5GZORRO/smart-contract-lifecycle-manager/eu/_5gzorro/contracts/0.1/contracts-0.1.jar
        - url: https://maven.pkg.github.com/5GZORRO/smart-contract-lifecycle-manager/eu/_5gzorro/did-oracle/0.1/did-oracle-0.1.jar
        - url: https://maven.pkg.github.com/5GZORRO/smart-contract-lifecycle-manager/eu/_5gzorro/workflows/0.1/workflows-0.1.jar
        
    volume:
      baseDir: /base/corda
    resources:
      limits: "1Gi"
      requests: "1Gi" 
    pvc:
      name: notary-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: azurestorageclass

    service:
      name: notary
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
        targetPort: 10003 
      rpcadmin:
        port: 10005
        targetPort: 10005
         
    deployment:
      annotations: {}
    vault:
      address: http://vault.5gzorro.smartcommunitylab.it:8200
      role: vault-role
      authpath: cordanotary
      serviceaccountname: vault-auth
      dbsecretprefix: notary/data/credentials/database
      rpcusersecretprefix: notary/data/credentials/rpcusers
      keystoresecretprefix: notary/data/credentials/keystore
      certsecretprefix: notary/data/certs
      networkmapsecretprefix: notary/data/credentials/networkmappassword
      cordappsreposecretprefix: notary/data/credentials/cordapps
      retries: 10

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: notary
      external_url_suffix: corda.5gzorro.smartcommunitylab.it
      p2p_ambassador: 15010
