apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store
  annotations:
    fluxcd.io/automated: "false"
  namespace: store-ns
spec:
  releaseName: store
  interval: 1m
  chart:
    spec:
      chart: platforms/r3-corda/charts/node
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
  values:
    nodeName: store
    replicas: 1
    metadata:
      namespace: store-ns
    image:
      containerName: ghcr.io/hyperledger/bevel-corda:4.7-linuxkit
      initContainerName: ghcr.io/hyperledger/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: doorman.corda.5gzorro.smartcommunitylab.it
      networkmapCertAlias: networkmap.corda.5gzorro.smartcommunitylab.it
    nodeConf:
      p2p:
        url: store.store-ns
        port: 10002
      ambassadorAddress: store.corda.5gzorro.smartcommunitylab.it:15020
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Store,OU=Store,L=40.73/-74/New York,C=US #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
       
      detectPublicIp: false
      database:
        exportHibernateJMXStatistics: false
      dbUrl: storedb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://storedb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: https://networkmap.corda.5gzorro.smartcommunitylab.it
      doormanURL: https://doorman.corda.5gzorro.smartcommunitylab.it
      compatibilityZoneURL:
      jarVersion: 4.7
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: storeoperations
          permissions: [ALL]

    cordapps:
      getcordapps: false

    volume:
      baseDir: /base/corda
    resources:
      limits: "1Gi"
      requests: "1Gi" 
    pvc:
      name: store-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: azurestorageclass

    service:
      name: store
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
        targetPort: 10003 
      rpcadmin:
        port: 10005
        targetPort: 10005
         
    deployment:
      annotations: {}
    vault:
      address: http://vault.5gzorro.smartcommunitylab.it:8200
      role: vault-role
      authpath: cordastore
      serviceaccountname: vault-auth
      dbsecretprefix: store/data/credentials/database
      rpcusersecretprefix: store/data/credentials/rpcusers
      keystoresecretprefix: store/data/credentials/keystore
      certsecretprefix: store/data/certs
      networkmapsecretprefix: store/data/credentials/networkmappassword
      cordappsreposecretprefix: store/data/credentials/cordapps
      retries: 10

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: store
      external_url_suffix: corda.5gzorro.smartcommunitylab.it
      p2p_ambassador: 15020
